// UniHolder - single-file Customizer version, generated by tools/build_single_file.py.
// Same model as uniholder.scad + lib/ in one file (tested identical geometry).
// =====================================================================
//  UniHolder — parametric universal holder                        v1.0
//  MSF 3D Printing for All · OpenSCAD 2021.01 or newer · no libraries
//
//  Print exactly as generated: standing on its floor, without supports.
//  No downward-facing surface exceeds max_overhang.
//
//  v1.0 (ST-5): DIN rail clip, single-file Customizer version, zip-tie clearance.
//  v0.4 (ST-4): vertical and horizontal pole mounts with zip-tie tunnels.
//               Screw heads seat flush: the back wall thickens, nothing enters the item space.
//  v0.3 (ST-3): back holes; wings with holes and gussets; cleaner F5 preview.
//  v0.2 (ST-2): body, wall styles, hexagon pattern, front opening.
// =====================================================================

/* [Print] */
// What to generate: holder, DIN rail clip, both on one bed, or din_preview (clip shown mounted, for viewing only)
part = "holder"; // [holder, din_clip, holder_and_clip, din_preview]
// Largest overhang in degrees from vertical (60 default, 45 for weak part cooling)
max_overhang = 60; // [40:5:60]
// Render quality
quality = "normal"; // [draft, normal, fine]

/* [Size] */
// inner = size of the item, outer = size of the finished holder
size_mode = "inner"; // [inner, outer]
// Width (X)
size_x = 60; // [10:0.5:400]
// Depth (Y), front to back
size_y = 40; // [10:0.5:400]
// Height (Z)
size_z = 80; // [10:0.5:400]
// Clearance around the item on each side (inner mode)
item_clr = 1; // [0:0.1:10]

/* [Walls and edges] */
// Side and front wall thickness
wall_t = 2.4; // [1.2:0.1:8]
// Back wall thickness (mounting side)
back_t = 3.2; // [1.6:0.1:10]
// Floor thickness
floor_t = 2; // [0.8:0.1:8]
// Radius of the front vertical edges
corner_r = 6; // [0:0.5:40]
// Radius of the back vertical edges
back_corner_r = 1.5; // [0:0.5:40]
// Chamfer of the top edges
chamfer_top = 1; // [0:0.1:5]
// Chamfer of the edges on the print bed
chamfer_bottom = 0.6; // [0:0.1:3]
// Inner chamfer between floor and walls
floor_cove = 2; // [0:0.5:10]

/* [Wall styles] */
back_style = "solid"; // [solid, hex]
left_style = "hex"; // [solid, hex]
right_style = "hex"; // [solid, hex]
// open = cut down to a retaining lip, slot = narrow vertical slot
front_style = "open"; // [solid, hex, open, slot]
floor_style = "solid"; // [solid, hex]

/* [Hex pattern] */
// Hexagon hole width across flats
hex_size = 8; // [3:0.5:40]
// Material between hexagons
hex_strut = 2; // [1.2:0.1:10]
// Solid border at the wall ends
hex_margin = 3; // [1:0.5:30]
// Solid band below the rim
hex_top_band = 6; // [0:0.5:50]
// Solid band above the floor
hex_bottom_band = 4; // [0:0.5:50]

/* [Front opening] */
// Height of the retaining lip above the inner floor (open)
front_lip_h = 20; // [0:0.5:400]
// Width of the retaining edges left and right (open)
front_side_lip_w = 8; // [1.2:0.5:100]
// Radius of the lower corners of the opening (open)
front_open_r = 5; // [0:0.5:50]
// Slot width (slot)
front_slot_w = 12; // [3:0.5:200]
// Height of the slot bottom above the inner floor (slot)
front_slot_z = 15; // [0:0.5:400]

/* [Back holes] */
// Screw holes in the back wall; screws go in from inside the holder
back_holes = true;
// Hole diameter (screw shank clearance)
back_hole_d = 4.5; // [3:0.5:10]
// countersink, counterbore and keyhole seat the head flush inside the back wall (it thickens as needed); plain leaves the head on the inner face
back_hole_style = "countersink"; // [plain, countersink, counterbore, keyhole]
// Screw head diameter including clearance (0 = 2 × hole diameter)
back_hole_head_d = 0; // [0:0.5:22]
// Number of hole columns
back_hole_cols = 1; // [1:1:6]
// Number of hole rows
back_hole_rows = 2; // [1:1:6]
// Horizontal hole spacing (0 = spread across the back wall)
back_hole_pitch_x = 0; // [0:0.5:300]
// Vertical hole spacing (0 = spread over the height)
back_hole_pitch_z = 0; // [0:0.5:300]

/* [Wings] */
// Mounting wings, flush with the back face
wings = "none"; // [none, left, right, both]
// Wing length beyond the side wall
wing_len = 20; // [8:1:100]
// Wing thickness
wing_t = 4; // [2:0.5:10]
// Wing height at the tip (0 = holder height)
wing_h = 0; // [0:1:400]
// bottom = wing stands on the bed; top = wing hangs from the rim with a support slope below
wing_align = "bottom"; // [bottom, top]
// Hole diameter
wing_hole_d = 4.5; // [3:0.5:10]
// slot = vertical slot for levelling
wing_hole_style = "countersink"; // [plain, countersink, slot]
// Holes per wing
wing_hole_count = 2; // [1:1:4]
// Triangular gusset between wing and side wall
wing_gusset = true;

/* [Pole mount] */
// Mount on a round pole with zip ties (replaces the back holes)
pole_mount = "none"; // [none, vertical, horizontal]
// Pole diameter
pole_d = 25; // [8:0.5:80]
// Included angle of the V-cradle; horizontal poles need at least 2 × (90 − max_overhang)
pole_v_angle = 90; // [60:5:150]
// Number of zip ties
tie_count = 2; // [1:1:6]
// Zip tie width (standard ties: 5 mm)
tie_w = 5; // [2:0.5:14]
// Zip tie thickness (standard ties: 2 mm)
tie_t = 2; // [1:0.1:4]
// Clearance added to the tunnels on width and thickness
tie_clr = 0.5; // [0:0.1:2]

/* [DIN rail clip] */
// Bolt holes for the DIN rail clip in the back wall; the clip is a separate part (Print tab: part)
din_holes = false;
// Bolts joining holder and clip (hole, head and nut sizes follow)
din_bolt = "M4"; // [M3, M4, M5, M6]
// Height of the rail centreline on the holder (0 = automatic)
din_rail_z = 0; // [0:0.5:400]
// Clip width along the rail (0 = automatic)
din_clip_w = 0; // [0:1:100]

/* [Hidden] */
// ==== begin lib/uh_core.scad ====
// =====================================================================
//  UniHolder — lib/uh_core.scad                                   ST-1
//  Constants, overhang math, hexagon math and console helpers.
//
//  Dependency-free; OpenSCAD 2021.01 language subset.
//  Libraries never include each other. Include them in this order:
//      include <lib/uh_core.scad>
//      include <lib/uh_shapes.scad>
//
//  Conventions (design plan §3–§4)
//    * Overhang angles are measured FROM VERTICAL: 0° = wall, 90° = ceiling.
//    * beta = 90° − max_overhang is the minimum rise of any downward-facing
//      surface above horizontal (the "roof angle").
//    * +Z is up in use and on the print bed. Units: mm and degrees.
//
//  Public API
//    Generic     uh_clamp  uh_auto  uh_approx  uh_quality  uh_fragments  uh_poly_r
//    Overhang    uh_beta  uh_rise  uh_run  uh_teardrop_apex  uh_roof_h
//                uh_overhang_of_nz  uh_flare_len  uh_chamfer_h  uh_chamfer_depth
//                uh_countersink_depth  uh_metric
//    Hexagon     uh_hex_flank  uh_hex_peak  uh_hex_dims  uh_hex_pitch
//    Console     uh_warn  uh_info  uh_warn_f  uh_clamp_warn
//    Transforms  uh_mirror_copy
//    Tests       uh_core_selftest
// =====================================================================

UH_CORE_VERSION = "0.1.0";

UH_EPS  = 0.01;    // overlap on coincident union / difference faces
UH_TINY = 0.001;   // thickness of construction slices
UH_BIG  = 4000;    // size of clipping volumes

UH_OVERHANG_MIN = 40;   // supported range of max_overhang
UH_OVERHANG_MAX = 60;

// ---------------------------------------------------------------------
//  Generic helpers
// ---------------------------------------------------------------------

function uh_clamp(x, lo, hi) = min(max(x, lo), hi);

// "0 means auto" convention for optional dimensions
function uh_auto(value, auto_value) = value == 0 ? auto_value : value;

function uh_approx(a, b, tol = 1e-6) = abs(a - b) <= tol;

// Quality preset -> [$fa, $fs]
function uh_quality(q) =
      q == "draft" ? [12, 1.0]
    : q == "fine"  ? [3, 0.2]
    :                [6, 0.4];

// Fragments OpenSCAD uses for a circle of radius r (same rule as the renderer)
function uh_fragments(r) =
      r < 1e-5 ? 3
    : $fn > 0  ? max($fn, 3)
    :            ceil(max(min(360 / $fa, r * 2 * PI / $fs), 5));

// Vertex radius of an n-gon whose flats sit at radius r.
// Used for clearance holes, so a printed hole is never undersized.
function uh_poly_r(r, n) = r / cos(180 / n);

// ---------------------------------------------------------------------
//  Overhang math (rules P2, P4, P5, P6)
// ---------------------------------------------------------------------

// Roof angle: minimum rise of a downward-facing surface above horizontal
function uh_beta(max_overhang) = 90 - max_overhang;

// Height a support slope gains over a horizontal run
function uh_rise(run, max_overhang) = run * tan(uh_beta(max_overhang));

// Horizontal run a support slope needs to gain a given height
function uh_run(rise, max_overhang) = rise / tan(uh_beta(max_overhang));

// Apex height above the centre of a teardrop with radius r
function uh_teardrop_apex(r, max_overhang) = r / cos(uh_beta(max_overhang));

// Height of a peaked roof over a flat span of width w
function uh_roof_h(w, max_overhang) = (w / 2) * tan(uh_beta(max_overhang));

// Overhang angle (from vertical) of a surface whose unit normal has z-component nz
function uh_overhang_of_nz(nz) = nz >= 0 ? 0 : asin(min(1, -nz));

// Axial length of an end flare that widens a channel by `flare` per side.
//   axis "x" / "y"  horizontal channel: the roof flare rises at >= 45° and >= beta
//   axis "z"        vertical channel:   the bottom flare stays <= 45° and <= max_overhang
function uh_flare_len(flare, max_overhang, axis = "x") =
      flare <= 0  ? 0
    : axis == "z" ? flare / min(1, tan(max_overhang))
    :               flare / max(1, tan(uh_beta(max_overhang)));

// Downward-facing chamfers (P9): a horizontal inset needs this much height,
// i.e. 45° while max_overhang >= 45 and steeper below that.
function uh_chamfer_h(inset, max_overhang) = inset * max(1, tan(uh_beta(max_overhang)));

// Face chamfer on a vertical plate: depth along the plate normal for a given inset,
// so the chamfer under a horizontal bottom edge also stays within max_overhang.
function uh_chamfer_depth(inset, max_overhang) = inset / max(1, tan(uh_beta(max_overhang)));

// Metric screws M3 ... M6: [clearance hole (ISO 273 medium), nut across flats, nut height
// (ISO 4032), countersunk head diameter (ISO 10642), cap head diameter, cap head height (ISO 4762)]
function uh_metric(size) =
      size == "M3" ? [3.4,  5.5, 2.4,  6.72,  5.5, 3]
    : size == "M5" ? [5.5,  8.0, 4.7, 11.20,  8.5, 5]
    : size == "M6" ? [6.6, 10.0, 5.2, 13.44, 10.0, 6]
    :                [4.5,  7.0, 3.2,  8.96,  7.0, 4];     // M4

// Depth of a countersink from bore d to head_d with the given included angle
function uh_countersink_depth(d, head_d, angle = 90) =
    max(0, (head_d - d) / 2) / tan(angle / 2);

// ---------------------------------------------------------------------
//  Hexagon math (rule P7) — pointy-top cell, across flats w (horizontal)
//  flank s = w/√3, peak h = (w/2)·tan(beta); beta = 30° gives the regular hexagon.
//  `grow` moves every edge outward (grid cell = hole grown by strut/2).
// ---------------------------------------------------------------------

function uh_hex_flank(w) = w / sqrt(3);

function uh_hex_peak(w, max_overhang) = (w / 2) * tan(uh_beta(max_overhang));

// [width, flank, peak, total height] of the (grown) cell
function uh_hex_dims(w, max_overhang, grow = 0) =
    let(b = uh_beta(max_overhang),
        s = uh_hex_flank(w) + 2 * grow * (1 - sin(b)) / cos(b),
        h = uh_hex_peak(w, max_overhang) + grow * tan(b))
    [w + 2 * grow, s, h, s + 2 * h];

// Honeycomb pitch [horizontal, vertical] for hole width w and strut width
function uh_hex_pitch(w, strut, max_overhang) =
    let(c = uh_hex_dims(w, max_overhang, strut / 2))
    [c[0], c[1] + c[2]];

// ---------------------------------------------------------------------
//  Console helpers
// ---------------------------------------------------------------------

module uh_warn(ok, msg) { if (!ok) echo(str("UH WARNING: ", msg)); }

module uh_info(msg) { echo(str("UH INFO: ", msg)); }

// Expression form: returns value, warns when ok is false
function uh_warn_f(ok, msg, value) =
    ok ? value : echo(str("UH WARNING: ", msg)) value;

// Clamp with a console warning naming the parameter
function uh_clamp_warn(x, lo, hi, name) =
    let(c = uh_clamp(x, lo, hi))
    c == x ? x : echo(str("UH WARNING: ", name, " = ", x, " clamped to ", c)) c;

// ---------------------------------------------------------------------
//  Transforms
// ---------------------------------------------------------------------

module uh_mirror_copy(v = [1, 0, 0]) { children(); mirror(v) children(); }

// ---------------------------------------------------------------------
//  Self-test (no geometry; asserts stop the render on failure)
// ---------------------------------------------------------------------

module uh_core_selftest() {
    t = 1e-6;
    p = uh_hex_pitch(8, 2, 60);
    q = uh_hex_pitch(8, 2, 45);
    assert(uh_approx(uh_beta(60), 30, t),                        "uh_beta");
    assert(uh_approx(uh_rise(10, 45), 10, t),                    "uh_rise at 45");
    assert(uh_approx(uh_rise(10, 60), 10 * tan(30), t),          "uh_rise at 60");
    assert(uh_approx(uh_run(uh_rise(7, 55), 55), 7, t),          "uh_run inverse");
    assert(uh_approx(uh_teardrop_apex(1, 45), sqrt(2), t),       "uh_teardrop_apex");
    assert(uh_approx(uh_hex_peak(8, 60), 8 / (2 * sqrt(3)), t),  "regular hexagon peak");
    assert(uh_approx(p[0], 10, t),                               "hex pitch u");
    assert(uh_approx(p[1], 10 * sqrt(3) / 2, t),                 "hex pitch v, regular");
    assert(q[1] > p[1],                                          "stretched hexagon is taller");
    assert(uh_approx(uh_countersink_depth(4.5, 9), 2.25, t),     "countersink depth");
    assert(uh_approx(uh_flare_len(1, 60, "x"), 1, t),            "flare length");
    assert(uh_approx(uh_chamfer_h(1, 60), 1, t),                 "chamfer 45° at 60");
    assert(uh_chamfer_h(1, 40) > 1,                              "chamfer steeper at 40");
    assert(uh_metric("M6")[1] == 10 && uh_metric("M3")[0] == 3.4, "metric screw table");
    uh_info("uh_core self-test passed");
}
// ==== end lib/uh_core.scad ====
// ==== begin lib/uh_shapes.scad ====
// =====================================================================
//  UniHolder — lib/uh_shapes.scad                                 ST-1
//  Printable primitives. Every downward-facing surface they create
//  respects max_overhang (design plan rules P2–P7, E1–E4).
//  Requires lib/uh_core.scad to be included first.
//
//  Frames
//    2D profiles   local +Y becomes print +Z when a 3D module places them.
//    Cutters       entry face at y = 0; the feature runs into material toward −Y;
//                  +Z up. Screw heads sit on the far (−Y) face.
//    Additions     grow out of a face at y = 0 toward +Y (dir = 1) or −Y (dir = −1).
//    Stacks        built along +Z from 2D outlines in the XY plane.
//
//  Public API
//    2D  uh_circle         clearance circle, flats at nominal size
//        uh_rrect4         rounded rectangle, four corner radii
//        uh_round_convex   round convex corners of 2D children
//        uh_round_concave  fillet concave corners of 2D children
//        uh_teardrop2d     circle with roof at beta (P4)
//        uh_slot2d         vertical slot with teardrop top
//        uh_peaked_rect2d  rectangle with peaked roof (P5)
//        uh_arch2d         pointed-arch window profile
//        uh_cantilever2d   wing / tab outline with support slope, safe tip rounds
//        uh_hex_cell2d     pointy-top hexagon cell (P7)
//    3D  uh_face_extrude       2D (x, z) profile extruded along Y
//        uh_slice_stack        hull of offset slices (chamfers)
//        uh_chamfered_extrude  prism with bottom/top chamfers (P9, E2)
//        uh_chamfered_plate    plate along Y with chamfered faces
//        uh_teardrop_prism     horizontal teardrop hole (P4)
//        uh_peaked_prism       horizontal peaked channel (P5)
//        uh_screw_hole         plain / countersink / counterbore, optional slot
//        uh_keyhole            keyhole with head channel
//        uh_tunnel             flared tie / strap tunnel, horizontal or vertical
//        uh_supported_prism    protrusion with support slope below (P6)
// =====================================================================

_uh_shapes_requires_core =
    assert(!is_undef(UH_CORE_VERSION), "uh_shapes.scad: include lib/uh_core.scad first") 1;

// =====================================================================
//  2D primitives
// =====================================================================

// Clearance circle. With compensate = true the polygon's flats sit on d/2,
// so a screw of diameter d always fits.
module uh_circle(d, compensate = true) {
    n = uh_fragments(d / 2);
    circle(r = compensate ? uh_poly_r(d / 2, n) : d / 2, $fn = n);
}

// Rounded rectangle with individual corner radii.
// r = [r0, r1, r2, r3] for corners (−x,−y), (+x,−y), (+x,+y), (−x,+y);
// for a holder footprint that is front-left, front-right, back-right, back-left.
// A single number applies to all four corners.
// center = false puts the (−x,−y) corner on the origin.
module uh_rrect4(size, r = 0, center = true) {
    sx = size[0];
    sy = size[1];
    rr = is_list(r) ? r : [r, r, r, r];
    sg = [[-1, -1], [1, -1], [1, 1], [-1, 1]];
    translate(center ? [0, 0] : [sx / 2, sy / 2])
        hull()
            for (i = [0:3]) {
                ri = uh_clamp(rr[i], 0, min(sx, sy) / 2);
                if (ri > UH_TINY)
                    translate([sg[i][0] * (sx / 2 - ri), sg[i][1] * (sy / 2 - ri)])
                        circle(r = ri);
                else
                    translate([sg[i][0] * (sx / 2 - UH_TINY), sg[i][1] * (sy / 2 - UH_TINY)])
                        square(2 * UH_TINY, center = true);
            }
}

// Round the convex corners of 2D children with radius r
module uh_round_convex(r) { offset(r = r) offset(delta = -r) children(); }

// Fillet the concave corners of 2D children with radius r
module uh_round_concave(r) { offset(r = -r) offset(delta = r) children(); }

// Teardrop (P4): circle Ø d plus two roof lines rising at beta to an apex on +Y.
module uh_teardrop2d(d, max_overhang = 60, compensate = true) {
    n  = uh_fragments(d / 2);
    rp = compensate ? uh_poly_r(d / 2, n) : d / 2;
    hull() {
        circle(r = rp, $fn = n);
        polygon([[-UH_TINY, 0], [UH_TINY, 0], [0, uh_teardrop_apex(rp, max_overhang)]]);
    }
}

// Vertical slot of width d: round bottom centred on the origin, teardrop top at (0, len).
module uh_slot2d(d, len, max_overhang = 60, compensate = true) {
    hull() {
        uh_circle(d, compensate);
        translate([0, max(0, len)]) uh_teardrop2d(d, max_overhang, compensate);
    }
}

// Rectangle size = [w, h] with a peaked roof (P5) above it.
// center = true centres the rectangle part on the origin; otherwise its bottom sits on y = 0.
// r_bottom rounds the two bottom corners (upward-facing valleys in the part).
module uh_peaked_rect2d(size, max_overhang = 60, r_bottom = 0, center = true) {
    w  = size[0];
    h  = size[1];
    rb = uh_clamp(r_bottom, 0, min(w / 2, h));
    roof = uh_roof_h(w, max_overhang);
    translate([0, center ? -h / 2 : 0])
        hull() {
            if (rb > UH_TINY) {
                translate([-w / 2 + rb, rb]) circle(r = rb);
                translate([ w / 2 - rb, rb]) circle(r = rb);
            }
            polygon([[-w / 2, rb], [w / 2, rb], [w / 2, h], [0, h + roof], [-w / 2, h]]);
        }
}

// Pointed-arch window: sill on y = 0, vertical sides of height h, roof at beta.
module uh_arch2d(w, h, max_overhang = 60, r_bottom = 0) {
    uh_peaked_rect2d([w, h], max_overhang, r_bottom, center = false);
}

// Cantilever plate profile drawn as (x, z): attached along x = 0 for 0 <= z <= h and
// reaching out to x = len — the outline of a wing or tab (P6, E3, E4).
//   on_bed = false  underside rises from (0, 0) at beta; both tip corners rounded by r
//   on_bed = true   flat underside on z = 0; only the top tip corner is rounded
// The root corners are never rounded: a round below the root would turn through
// horizontal and create a small ceiling.
module uh_cantilever2d(len, h, max_overhang = 60, r = 0, on_bed = false) {
    k  = uh_rise(1, max_overhang);
    zt = on_bed ? 0 : len * k;                         // underside height at the tip
    rr = uh_clamp(r, 0, min(len, h - zt) / 2);
    assert(h - zt > 2 * rr + UH_TINY, "uh_cantilever2d: plate is too short for its support slope");
    cz = k * (len - rr) + rr * sqrt(1 + k * k);        // lower tip circle: tangent to slope and tip
    hull() {
        polygon([[0, 0],
                 on_bed ? [len, 0] : (rr > 0 ? [len - rr, cz] : [len, zt]),
                 rr > 0 ? [len - rr, h - rr] : [len, h],
                 [0, h]]);
        if (rr > 0) {
            translate([len - rr, h - rr]) circle(r = rr);
            if (!on_bed) translate([len - rr, cz]) circle(r = rr);
        }
    }
}

// Pointy-top hexagon (P7), across flats w, upper edges at beta.
// grow moves every edge outward, keeping strut widths uniform.
module uh_hex_cell2d(w, max_overhang = 60, grow = 0) {
    c = uh_hex_dims(w, max_overhang, grow);
    x = c[0] / 2;
    s = c[1] / 2;
    p = s + c[2];
    polygon([[0, p], [-x, s], [-x, -s], [0, -p], [x, -s], [x, s]]);
}

// =====================================================================
//  3D helpers
// =====================================================================

// Extrude a 2D profile drawn as (x, z) along Y:
// dir = −1 from y = 0 to y = −depth, dir = 1 from y = 0 to y = +depth,
// center = true from −depth/2 to +depth/2.
module uh_face_extrude(depth, dir = -1, center = false) {
    if (center)
        translate([0, depth / 2, 0]) rotate([90, 0, 0]) linear_extrude(depth, convexity = 10) children();
    else if (dir < 0)
        rotate([90, 0, 0]) linear_extrude(depth, convexity = 10) children();
    else
        mirror([0, 1, 0]) rotate([90, 0, 0]) linear_extrude(depth, convexity = 10) children();
}

// Hull of thin slices of offset(delta = d) children at heights z.
// levels = [[z0, d0], [z1, d1], ...] in ascending z; children = one convex 2D outline.
// pairwise = true hulls consecutive slices only — required whenever a middle slice
// is narrower than an outer one (e.g. a cavity that flares at the rim), because a
// single hull would taper the walls.
module uh_slice_stack(levels, pairwise = false) {
    n = len(levels);
    if (pairwise)
        render(convexity = 4)   // one solid: no internal faces that show as skins in the F5 preview
            for (i = [0:n - 2])
                hull() {
                    _uh_slice(levels[i], false) children();
                    _uh_slice(levels[i + 1], i + 1 == n - 1) children();
                }
    else
        hull()
            for (i = [0:n - 1]) _uh_slice(levels[i], i == n - 1) children();
}

module _uh_slice(level, is_top) {
    translate([0, 0, level[0] - (is_top ? UH_TINY : 0)])
        linear_extrude(UH_TINY) offset(delta = level[1]) children();
}

// Prism of height h from a convex 2D outline with chamfers:
// c_bot insets the bottom edge (P9) — 45°, or steeper when max_overhang < 45;
// c_top insets the top edge (E2) at 45°.
module uh_chamfered_extrude(h, c_bot = 0, c_top = 0, max_overhang = 60) {
    cb  = max(0, c_bot);
    ct  = uh_clamp(c_top, 0, h / 2);
    cbh = min(uh_chamfer_h(cb, max_overhang), h / 2);
    uh_slice_stack(concat(cb > 0 ? [[0, -cb], [cbh, 0]] : [[0, 0]],
                          ct > 0 ? [[h - ct, 0], [h, -ct]] : [[h, 0]]))
        children();
}

// Plate: convex 2D outline drawn as (x, z), extruded along Y by depth from y = 0
// toward dir, with chamfers of inset c_near (face at y = 0) and c_far (face at
// y = dir·depth). Chamfer depth follows max_overhang, so the chamfer under a
// bottom edge never exceeds the limit.
module uh_chamfered_plate(depth, c_far = 0, c_near = 0, dir = -1, max_overhang = 60) {
    cf = max(0, c_far);
    cn = max(0, c_near);
    tf = min(uh_chamfer_depth(cf, max_overhang), depth / 2);
    tn = min(uh_chamfer_depth(cn, max_overhang), depth / 2);
    lv = concat(cn > 0 ? [[0, -cn], [tn, 0]] : [[0, 0]],
                cf > 0 ? [[depth - tf, 0], [depth, -cf]] : [[depth, 0]]);
    if (dir < 0)
        rotate([90, 0, 0]) uh_slice_stack(lv) children();
    else
        mirror([0, 1, 0]) rotate([90, 0, 0]) uh_slice_stack(lv) children();
}

// =====================================================================
//  3D cutters (entry face y = 0, into material toward −Y)
// =====================================================================

// Horizontal teardrop hole (P4); center = true centres it on y = 0.
module uh_teardrop_prism(d, len, max_overhang = 60, center = false, compensate = true) {
    uh_face_extrude(len, -1, center) uh_teardrop2d(d, max_overhang, compensate);
}

// Horizontal channel with rectangular section size = [w, h] and a peaked roof (P5),
// section centred on the origin; center = true centres it on y = 0.
module uh_peaked_prism(size, len, max_overhang = 60, r_bottom = 0, center = false) {
    uh_face_extrude(len, -1, center) uh_peaked_rect2d(size, max_overhang, r_bottom, true);
}

// Screw hole through a wall of thickness t: enters at y = 0, head on the face y = −t.
//   style     "plain" | "countersink" | "counterbore"
//   head_d    head diameter, 0 = 2·d          cb_depth  counterbore depth
//   cs_angle  countersink included angle      head_ext  head clearance beyond y = −t
//   slot      vertical slot length (0 = round) for levelling
// All parts are teardrop-shaped (P4); the countersink is a teardrop cone.
module uh_screw_hole(d, t, style = "plain", head_d = 0, cb_depth = 3, cs_angle = 90,
                     head_ext = 0, slot = 0, max_overhang = 60, compensate = true) {
    mo  = max_overhang;
    hd  = uh_auto(head_d, 2 * d);
    csd = min(uh_countersink_depth(d, hd, cs_angle), t);
    cbd = uh_clamp(cb_depth, 0, t);
    uh_warn(style != "countersink" || csd <= t - 1.2,
            str("uh_screw_hole: countersink depth ", csd, " leaves less than 1.2 mm of wall"));
    uh_warn(style != "counterbore" || cbd <= t - 1.2,
            str("uh_screw_hole: counterbore depth ", cbd, " leaves less than 1.2 mm of wall"));

    render(convexity = 4) {   // one solid for a clean F5 preview
    // bore, from just outside y = 0 to just past the head face
    _uh_zspan(slot)
        translate([0, UH_EPS, 0]) uh_teardrop_prism(d, t + 2 * UH_EPS, mo, false, compensate);

    if (style == "countersink")
        _uh_zspan(slot)
            hull() {
                translate([0, -t + csd, 0])     uh_teardrop_prism(d,  UH_TINY, mo, false, compensate);
                translate([0, -t + UH_TINY, 0]) uh_teardrop_prism(hd, UH_TINY, mo, false, compensate);
            }

    if (style == "counterbore")
        _uh_zspan(slot)
            translate([0, -t + cbd, 0]) uh_teardrop_prism(hd, cbd + UH_EPS, mo, false, compensate);

    if (style == "countersink" || style == "counterbore")
        _uh_zspan(slot)
            translate([0, -t, 0]) uh_teardrop_prism(hd, head_ext + UH_EPS, mo, false, compensate);
    }
}

// Hull of children at z = 0 and z = len (vertical slot sweep); plain children if len = 0.
module _uh_zspan(len) {
    if (len > UH_TINY)
        hull() { children(); translate([0, 0, len]) children(); }
    else
        children();
}

// Keyhole for hanging on a screw head. Entry face y = 0 lies against the wall;
// the entry centre is on the origin and the shank slot rises by slot_len.
//   d        shank slot width               head_d   entry and head channel width
//   skin     outer skin thickness           head_h   head channel depth behind the skin
//   through  extra channel length, e.g. to open the pocket into the cavity (no blind pocket)
module uh_keyhole(d, head_d, slot_len, skin = 1.6, head_h = 3, through = 0,
                  max_overhang = 60, compensate = true) {
    mo = max_overhang;
    render(convexity = 4) {   // one solid for a clean F5 preview
    // outer skin: shank slot plus head entry
    translate([0, UH_EPS, 0])
        uh_face_extrude(skin + 2 * UH_EPS, -1) {
            uh_slot2d(d, slot_len, mo, compensate);
            uh_teardrop2d(head_d, mo, compensate);
        }
    // head channel behind the skin
    translate([0, -skin, 0])
        uh_face_extrude(head_h + through, -1) uh_slot2d(head_d, slot_len, mo, compensate);
    }
}

// Flared tunnel for zip ties, straps or hose clamps, centred on the origin.
//   axis "x"  horizontal along X: section w tall (Z) × t deep (Y), peaked roof (P5)
//   axis "z"  vertical along Z:   section w wide (X) × t deep (Y)
// len is the distance between the two faces; flare widens both ends by `flare` per side.
module uh_tunnel(w, t, len, flare = 0, axis = "x", max_overhang = 60) {
    mo = max_overhang;
    f  = max(0, flare);
    a  = len / 2 - uh_flare_len(f, mo, axis == "z" ? "z" : "x");
    b  = len / 2 + UH_EPS;
    assert(a > 0, "uh_tunnel: flares are longer than the tunnel");
    render(convexity = 4) if (axis == "z") {
        hull() { _uh_zslab(-a) square([w, t], center = true); _uh_zslab(a) square([w, t], center = true); }
        for (s = [-1, 1]) hull() {
            _uh_zslab(s * a) square([w, t], center = true);
            _uh_zslab(s * b) square([w + 2 * f, t + 2 * f], center = true);
        }
    } else {
        hull() { _uh_xslab(-a) uh_peaked_rect2d([t, w], mo); _uh_xslab(a) uh_peaked_rect2d([t, w], mo); }
        for (s = [-1, 1]) hull() {
            _uh_xslab(s * a) uh_peaked_rect2d([t, w], mo);
            _uh_xslab(s * b) uh_peaked_rect2d([t + 2 * f, w + 2 * f], mo);
        }
    }
}

// thin slab of a 2D profile: (a, b) -> (Y = a, Z = b) at X = x
module _uh_xslab(x) {
    translate([x, 0, 0]) rotate([90, 0, 90]) linear_extrude(UH_TINY, center = true) children();
}

// thin slab of a 2D profile in the XY plane at Z = z
module _uh_zslab(z) {
    translate([0, 0, z]) linear_extrude(UH_TINY, center = true) children();
}

// =====================================================================
//  3D additions
// =====================================================================

// Protrusion with a support slope below it (P6, "hull-down").
// Children: one convex 2D profile drawn as (x, z) in absolute heights.
// The profile is extruded out of the face at y = 0 by depth toward dir; its underside
// is supported by a slope rising at beta from the face. clip = true cuts at z = 0.
module uh_supported_prism(depth, max_overhang = 60, dir = 1, clip = true) {
    if (clip)
        render(convexity = 2)   // real bounding box in the F5 preview (View All), not the clip cube
            intersection() {
                _uh_supported_hull(depth, max_overhang, dir) children();
                translate([-UH_BIG / 2, -UH_BIG / 2, 0]) cube(UH_BIG);
            }
    else
        _uh_supported_hull(depth, max_overhang, dir) children();
}

module _uh_supported_hull(depth, max_overhang, dir) {
    hull() {
        uh_face_extrude(depth, dir) children();
        translate([0, 0, -uh_rise(depth, max_overhang)]) uh_face_extrude(UH_TINY, dir) children();
    }
}
// ==== end lib/uh_shapes.scad ====
// ==== begin lib/uh_body.scad ====
// =====================================================================
//  UniHolder — lib/uh_body.scad                                   ST-2
//  Holder body: derived dimensions, outer shell, cavity, hexagon
//  perforation of walls and floor, front opening.
//
//  Reads the Customizer parameters of uniholder.scad.
//  Include after uh_core.scad and uh_shapes.scad.
//  Frame: y = 0 is the mounting plane (outer back face) and the body
//  extends to −Y; x = 0 is the centreline; z = 0 is the print bed.
//
//  Public API
//    Values     MO  BACK_T  BODY_W  BODY_D  BODY_H  IN_X0  IN_X1  IN_Y0  IN_Y1  IN_W  IN_D
//               R_OUT  R_IN  C_BOT  C_TOP_OUT  C_TOP_IN  C_CUT  COVE
//    Modules    uh_body_checks  uh_outer_shell  uh_cavity  uh_item_space  uh_perforations
//               uh_front_opening  uh_wall_cut  uh_hex_grid2d
//    Functions  uh_wall_zone  uh_hex_cells  uh_keepouts
// =====================================================================

// ---- derived values ---------------------------------------------------

MO = uh_clamp_warn(max_overhang, UH_OVERHANG_MIN, UH_OVERHANG_MAX, "max_overhang");

// Back wall thickness. Screw heads must sit flush inside the wall: nothing may
// protrude into the item space, so the whole wall thickens instead of adding bosses.
// In inner mode the body grows backwards and the item space keeps its size.
KEY_SKIN  = 2.0;   // keyhole: wall-side skin that carries the screw head
KEY_HEAD  = 3.5;   // keyhole: head channel depth behind the skin
MIN_SKIN  = 1.2;   // material left behind a seated head
BH_ACTIVE = (back_holes || din_holes) && pole_mount == "none";   // a pole mount replaces the back holes
BH_DIN    = din_holes && BH_ACTIVE;                               // holes follow the DIN clip bolts
BH_BOLT   = uh_metric(din_bolt);
BH_STYLE  = (BH_DIN && back_hole_style == "keyhole") ? "countersink" : back_hole_style;
BH_DIA    = BH_DIN ? BH_BOLT[0] : back_hole_d;                    // hole diameter
BH_HEAD   = !BH_DIN ? uh_auto(back_hole_head_d, 2 * back_hole_d)  // screw head incl. clearance
          : BH_STYLE == "counterbore" ? BH_BOLT[4] + 0.6 : BH_BOLT[3] + 0.5;
CB_DEPTH  = BH_DIN ? BH_BOLT[5] + 0.4 : 3.0;                      // counterbore depth
BH_NEED   = !BH_ACTIVE ? 0
          : BH_STYLE == "countersink" ? uh_countersink_depth(BH_DIA, BH_HEAD) + MIN_SKIN
          : BH_STYLE == "counterbore" ? CB_DEPTH + MIN_SKIN
          : BH_STYLE == "keyhole"     ? KEY_SKIN + KEY_HEAD + MIN_SKIN
          :                             MIN_SKIN;
BACK_T    = max(back_t, BH_NEED);

BODY_W = size_mode == "inner" ? size_x + 2 * item_clr + 2 * wall_t : size_x;
BODY_D = size_mode == "inner" ? size_y + 2 * item_clr + wall_t + BACK_T : size_y;
BODY_H = size_mode == "inner" ? size_z + floor_t : size_z;

T_MIN    = min(wall_t, BACK_T);
R_IN_MIN = 1.5;                                    // inner corners stay cleanable

// corner radii: front-left, front-right, back-right, back-left
R_OUT = [for (r = [corner_r, corner_r, back_corner_r, back_corner_r])
            uh_clamp(r, 0, min(BODY_W, BODY_D) / 2)];
R_IN  = [for (r = R_OUT) max(r - T_MIN, R_IN_MIN)];

IN_X0 = -BODY_W / 2 + wall_t;    IN_X1 = BODY_W / 2 - wall_t;
IN_Y0 = -BODY_D + wall_t;        IN_Y1 = -BACK_T;
IN_W  = IN_X1 - IN_X0;           IN_D  = IN_Y1 - IN_Y0;

C_BOT     = uh_clamp(chamfer_bottom, 0, min(floor_t, T_MIN / 2));
C_TOP_OUT = uh_clamp(chamfer_top, 0, T_MIN / 2);
C_TOP_IN  = uh_clamp(chamfer_top, 0, max(0, T_MIN - C_TOP_OUT - 0.8));   // keeps a 0.8 mm flat rim
C_CUT     = uh_clamp(chamfer_top, 0, max(0, (wall_t - 0.8) / 2));        // edges of front cut-outs
COVE      = uh_clamp(floor_cove, 0, max(0, min(IN_W, IN_D) / 4));

// distance from a wall end to the straight, perforable part of the wall
CLR_FRONT = max(R_OUT[0], wall_t + R_IN[0]);      // side walls at the front, front wall at the sides
CLR_BACK  = max(R_OUT[2], BACK_T + R_IN[2]);      // side walls at the back
CLR_BACKS = max(R_OUT[2], wall_t + R_IN[2]);      // back wall at the sides

HEX_V0 = floor_t + COVE + hex_bottom_band;        // perforation height range on walls
HEX_V1 = BODY_H - C_TOP_OUT - hex_top_band;

LIP_W  = uh_clamp_warn(front_side_lip_w, wall_t, max(wall_t, BODY_W / 2 - 2), "front_side_lip_w");
LIP_Z  = floor_t + uh_clamp(front_lip_h, 0, max(0, BODY_H - floor_t - 5));
OPEN_W = BODY_W - 2 * LIP_W;
SLOT_W = uh_clamp_warn(front_slot_w, 3, max(3, BODY_W - 2 * CLR_FRONT - 2), "front_slot_w");
SLOT_Z = floor_t + uh_clamp(front_slot_z, 0, max(0, BODY_H - floor_t - 5));

// ---- checks -----------------------------------------------------------

module uh_body_checks() {
    assert(IN_W >= 5 && IN_D >= 5,
        "UniHolder: inner space is below 5 mm - increase the size or reduce the wall thickness");
    assert(BODY_H >= floor_t + 5, "UniHolder: height must exceed the floor by at least 5 mm");
    uh_info(str("outer ", BODY_W, " x ", BODY_D, " x ", BODY_H, " mm, inner ",
                IN_W, " x ", IN_D, " x ", BODY_H - floor_t, " mm"));
}

// ---- shell and cavity -------------------------------------------------

module uh_outer_shell() {
    uh_chamfered_extrude(BODY_H, C_BOT, C_TOP_OUT, MO)
        translate([0, -BODY_D / 2]) uh_rrect4([BODY_W, BODY_D], R_OUT);
}

// Pairwise hull: floor cove (upward-facing), straight walls, flared rim
module uh_cavity() {
    lv = concat(COVE > 0 ? [[floor_t, -COVE], [floor_t + COVE, 0]] : [[floor_t, 0]],
                C_TOP_IN > 0 ? [[BODY_H - C_TOP_IN, 0], [BODY_H + 1, C_TOP_IN + 1]]
                             : [[BODY_H + 1, 0]]);          // cut ends 1 mm above the rim
    uh_slice_stack(lv, pairwise = true)
        translate([(IN_X0 + IN_X1) / 2, (IN_Y0 + IN_Y1) / 2]) uh_rrect4([IN_W, IN_D], R_IN);
}

// The clear item space (straight part of the cavity, inset 0.05 mm). Test hook:
// intersecting it with the holder must give nothing.
module uh_item_space() {
    translate([0, 0, floor_t + COVE + 0.05])
        linear_extrude(BODY_H - floor_t - COVE)
            offset(delta = -0.05)
                translate([(IN_X0 + IN_X1) / 2, (IN_Y0 + IN_Y1) / 2]) uh_rrect4([IN_W, IN_D], R_IN);
}

// ---- hexagon perforation ------------------------------------------------

// Wall zone [u0, v0, u1, v1] in wall-local coordinates:
// back, front: u = x;  left, right: u = y;  floor: u = x, v = y
function uh_wall_zone(wall) =
      wall == "back"  ? [-BODY_W / 2 + CLR_BACKS + hex_margin, HEX_V0, BODY_W / 2 - CLR_BACKS - hex_margin, HEX_V1]
    : wall == "front" ? [-BODY_W / 2 + CLR_FRONT + hex_margin, HEX_V0, BODY_W / 2 - CLR_FRONT - hex_margin, HEX_V1]
    : wall == "floor" ? [IN_X0 + COVE + hex_margin, IN_Y0 + COVE + hex_margin,
                         IN_X1 - COVE - hex_margin, IN_Y1 - COVE - hex_margin]
    :                   [-BODY_D + CLR_FRONT + hex_margin, HEX_V0, -CLR_BACK - hex_margin, HEX_V1];

// Keepout rectangles per wall, published by the mount library (uh_mount.scad)
function uh_keepouts(wall) = uh_mount_keepouts(wall);

// Centres of whole hexagon cells that fit the zone and miss every keepout.
// Rows alternate between n and n − 1 cells, so the pattern stays centred.
function uh_hex_cells(zone, w, strut, mo, keepouts = []) =
    let(cell = uh_hex_dims(w, mo),
        p    = uh_hex_pitch(w, strut, mo),
        zu   = zone[2] - zone[0],
        zv   = zone[3] - zone[1],
        rows = floor((zv - cell[3]) / p[1]) + 1,
        cols = floor((zu - w) / p[0]) + 1,
        uc   = (zone[0] + zone[2]) / 2,
        v0   = zone[1] + (zv - ((rows - 1) * p[1] + cell[3])) / 2 + cell[3] / 2,
        half = [w / 2 + strut, cell[3] / 2 + strut])
    (rows < 1 || cols < 1) ? [] :
    [for (r = [0:rows - 1])
        let(n = r % 2 == 0 ? cols : cols - 1)
        if (n > 0)
            for (c = [0:n - 1])
                let(pt = [uc + (c - (n - 1) / 2) * p[0], v0 + r * p[1]])
                if (!_uh_hits(pt, half, keepouts)) pt];

function _uh_hits(pt, half, ks) =
    len([for (k = ks)
            if (pt[0] - half[0] < k[2] && pt[0] + half[0] > k[0] &&
                pt[1] - half[1] < k[3] && pt[1] + half[1] > k[1]) 1]) > 0;

module uh_hex_grid2d(cells, w, mo) {
    for (p = cells) translate(p) uh_hex_cell2d(w, mo);
}

// Place a 2D wall-local pattern as a cutter through the given wall
module uh_wall_cut(wall) {
    if (wall == "back")
        translate([0, -BACK_T / 2, 0]) uh_face_extrude(BACK_T + 2, center = true) children();
    else if (wall == "front")
        translate([0, -BODY_D + wall_t / 2, 0]) uh_face_extrude(wall_t + 2, center = true) children();
    else if (wall == "left")
        translate([-BODY_W / 2 + wall_t / 2, 0, 0]) rotate([0, 0, 90])
            uh_face_extrude(wall_t + 2, center = true) children();
    else if (wall == "right")
        translate([BODY_W / 2 - wall_t / 2, 0, 0]) rotate([0, 0, 90])
            uh_face_extrude(wall_t + 2, center = true) children();
    else if (wall == "floor")
        translate([0, 0, -1]) linear_extrude(floor_t + 2, convexity = 10) children();
}

module uh_perforations() {
    for (ws = [["back", back_style], ["front", front_style], ["left", left_style],
               ["right", right_style], ["floor", floor_style]])
        if (ws[1] == "hex") {
            cells = uh_hex_cells(uh_wall_zone(ws[0]), hex_size, hex_strut, MO, uh_keepouts(ws[0]));
            uh_warn(len(cells) > 0, str(ws[0], ": no room for a whole hexagon, wall stays solid"));
            if (len(cells) > 0) uh_wall_cut(ws[0]) uh_hex_grid2d(cells, hex_size, MO);
        }
}

// ---- front opening ------------------------------------------------------

module uh_front_opening() {
    if (front_style == "open")
        _uh_front_cut(OPEN_W, LIP_Z, [front_open_r, front_open_r, 0, 0],
                      wall_t + R_IN[0], min(C_CUT, front_lip_h));
    else if (front_style == "slot")
        _uh_front_cut(SLOT_W, SLOT_Z, [SLOT_W / 2, SLOT_W / 2, 0, 0],
                      wall_t + 1, min(C_CUT, front_slot_z));
}

// Cut-out through the front wall: w wide, from height z0 to above the rim,
// lower corners rounded by r. Edges get a chamfer c on the outer and inner face
// (pairwise slice stack along +Y; all chamfer faces look upward or sideways).
module _uh_front_cut(w, z0, r, depth, c) {
    translate([0, -BODY_D - 1, 0]) mirror([0, 1, 0]) rotate([90, 0, 0])
        uh_slice_stack([[0, c + 1], [1 + c, 0], [1 + wall_t - c, 0],
                        [1 + wall_t, c], [1 + depth + UH_EPS, c]], pairwise = true)
            translate([-w / 2, z0]) uh_rrect4([w, BODY_H - z0 + 1], r, center = false);
}
// ==== end lib/uh_body.scad ====
// ==== begin lib/uh_din.scad ====
// =====================================================================
//  UniHolder — lib/uh_din.scad                                    ST-5
//  Clip for TS35 × 7.5 DIN rail (EN 60715), printed as a separate part.
//
//  The clip is one 2D profile extruded along the rail and printed lying on
//  that profile: every wall is vertical in print (no supports), and the
//  spring beams bend within the layers.
//    * fixed hook on top; spring latch below with a 45° lead-in ramp
//    * zig-zag spring of thin in-plane beams; release tab below the spring
//    * two nuts (M3 ... M6, din_bolt) in hexagonal pockets; the holder is bolted
//      on with two screws through its DIN hole pattern (din_holes)
//  Mounting: hook the top over the rail and press the bottom until the latch
//  snaps. Removal: lever the release tab down with a flat screwdriver.
//
//  Profile frame (u, v): u = distance from the holder's back face toward the
//  panel, v = height above the rail centreline; the rail lips rest on the
//  plate face u = DIN_P. Include after uh_body.scad, before uh_mount.scad.
// =====================================================================

// TS35 × 7.5 rail
DIN_E       = 17.5;   // half width over the lips
DIN_LIP_W   = 4.0;    // lip width (lip roots at |v| = 13.5)
DIN_DEPTH   = 7.5;    // lip face to panel
DIN_LIP_T   = 1.5;    // lip thickness allowed (standard rails are 1.0 mm)

// bolts joining holder and clip (M3 ... M6)
DIN_BOLT       = uh_metric(din_bolt);
DIN_BOLT_PITCH = din_bolt == "M6" ? 24 : 20;     // bolt spacing along the rail
DIN_BOLT_D     = DIN_BOLT[0];                    // clearance hole
DIN_NUT_AF     = DIN_BOLT[1] + 0.4;              // nut pocket across flats
DIN_NUT_H      = DIN_BOLT[2] + 0.4;              // nut pocket depth

// clip profile
DIN_P       = max(5.0, DIN_NUT_H + MIN_SKIN);    // plate thickness (holds the nut); lips rest on u = DIN_P
DIN_CLR     = 0.3;
DIN_TOOTH_U = 2.0;    // tooth thickness behind the lip
DIN_TOOTH_V = 2.5;    // tooth engagement behind the lip edge
DIN_ARM     = 3.0;    // hook arm thickness
DIN_PRELOAD = 0.5;    // latch overlaps the lip edge at rest (spring preload)
DIN_GAP     = 0.5;    // gap between moving and fixed parts
DIN_SPINE   = 2.5;    // plate spine beside the spring
DIN_BEAM_T  = 0.9;    // spring beam thickness (two perimeters)
DIN_BEAM_G  = 0.8;    // gap between spring beams
DIN_BEAMS   = 9;      // odd: the last beam meets the anchor on the spine side
DIN_CONN    = 1.0;    // spring connector width
DIN_ROD     = 0.8;    // release rod thickness
DIN_SLOT    = 1.5;    // screwdriver slot above the release tab
DIN_TAB     = 2.5;    // release tab height

// derived: u
DIN_UT   = DIN_P + DIN_LIP_T;                     // tooth front face
DIN_UB   = DIN_UT + DIN_TOOTH_U;                  // hook tooth back face
DIN_UMAX = DIN_P + DIN_DEPTH - 0.3;               // clear of the panel
DIN_U0   = DIN_SPINE + DIN_GAP;                   // front of the moving parts
DIN_US   = DIN_UMAX - DIN_ROD - DIN_GAP;          // far end of the spring
// derived: v (rest state)
DIN_V_TOP    = DIN_E + DIN_CLR + DIN_ARM;         // top of the clip
DIN_LB_TOP   = -DIN_E + DIN_PRELOAD;              // latch top face
DIN_T_TOP    = DIN_LB_TOP + DIN_TOOTH_V;          // latch tooth top
DIN_RAMP_V   = -DIN_E - 1;                        // lead-in ramp ends below the lip edge
DIN_RAMP_U   = DIN_UT + 0.4 + (DIN_T_TOP - DIN_RAMP_V);   // 45° ramp
DIN_LB_BOT   = DIN_RAMP_V - 2;
function _din_beam_top(i) = DIN_LB_BOT - DIN_BEAM_G - i * (DIN_BEAM_T + DIN_BEAM_G);
DIN_ANCH_TOP = _din_beam_top(DIN_BEAMS - 1) - DIN_BEAM_T - DIN_BEAM_G;
DIN_ANCH_BOT = DIN_ANCH_TOP - 3;
DIN_TAB_TOP  = DIN_ANCH_BOT - DIN_SLOT;
DIN_V_BOT    = DIN_TAB_TOP - DIN_TAB;             // bottom of the clip
DIN_PLATE_LO = DIN_LB_TOP + DIN_GAP;              // plate underside above the latch
DIN_W_MIN    = DIN_BOLT_PITCH + 2 * (uh_hex_dims(DIN_NUT_AF, MO)[3] / 2 + 1.2);
DIN_W        = din_clip_w > 0 ? din_clip_w : max(36, ceil(DIN_W_MIN));   // clip width along the rail

// screw length: through the holder's back wall and the clip plate into the nut
DIN_SCREW_MIN = (BH_STYLE == "counterbore" ? BACK_T - CB_DEPTH : BACK_T) + DIN_P - 0.4;
DIN_SCREW_L   = let(c = [for (l = [6, 8, 10, 12, 16, 20, 25, 30, 35, 40]) if (l >= DIN_SCREW_MIN) l])
                len(c) > 0 ? c[0] : ceil(DIN_SCREW_MIN);

module _uh_din_r(u0, v0, u1, v1) { translate([u0, v0]) square([u1 - u0, v1 - v0]); }

// fixed part: plate, hook, spine, spring anchor
module _uh_din_fixed2d() {
    _uh_din_r(0, DIN_PLATE_LO, DIN_P, DIN_V_TOP);
    _uh_din_r(DIN_P - 0.01, DIN_E + DIN_CLR, DIN_UB, DIN_V_TOP);
    polygon([[DIN_UT, DIN_E + DIN_CLR + 0.01], [DIN_UT, DIN_E - DIN_TOOTH_V],
             [DIN_UB - 1.2, DIN_E - DIN_TOOTH_V], [DIN_UB, DIN_E - DIN_TOOTH_V + 1.2],
             [DIN_UB, DIN_E + DIN_CLR + 0.01]]);
    _uh_din_r(0, DIN_ANCH_BOT, DIN_SPINE, DIN_PLATE_LO + 0.01);
    _uh_din_r(0, DIN_ANCH_BOT, DIN_US, DIN_ANCH_TOP);
}

// moving part: latch with tooth and ramp, zig-zag spring, release rod and tab
module _uh_din_latch2d() {
    polygon([[DIN_U0, DIN_LB_BOT], [DIN_U0, DIN_LB_TOP], [DIN_UT, DIN_LB_TOP], [DIN_UT, DIN_T_TOP],
             [DIN_UT + 0.4, DIN_T_TOP], [DIN_RAMP_U, DIN_RAMP_V], [DIN_UMAX, DIN_RAMP_V],
             [DIN_UMAX, DIN_LB_BOT]]);
    for (i = [0:DIN_BEAMS - 1])
        _uh_din_r(DIN_U0, _din_beam_top(i) - DIN_BEAM_T, DIN_US, _din_beam_top(i));
    for (k = [0:DIN_BEAMS]) {
        above = k == 0 ? DIN_LB_BOT : _din_beam_top(k - 1) - DIN_BEAM_T;
        below = k == DIN_BEAMS ? DIN_ANCH_TOP : _din_beam_top(k);
        cu = k % 2 == 0 ? DIN_US - DIN_CONN : DIN_U0;
        _uh_din_r(cu, below - 0.01, cu + DIN_CONN, above + 0.01);
    }
    _uh_din_r(DIN_US + DIN_GAP, DIN_TAB_TOP - 0.01, DIN_UMAX, DIN_LB_BOT + 0.01);
    _uh_din_r(DIN_U0, DIN_V_BOT, DIN_UMAX, DIN_TAB_TOP);
}

module uh_din_profile2d() { _uh_din_fixed2d(); _uh_din_latch2d(); }

// The clip in print orientation: profile on the bed, rail axis = +Z
module uh_din_clip() {
    assert(DIN_W >= DIN_W_MIN, str("UniHolder: din_clip_w must be at least ", ceil(DIN_W_MIN), " mm for ", din_bolt, " nuts"));
    difference() {
        linear_extrude(DIN_W, convexity = 10) uh_din_profile2d();
        for (s = [-1, 1])
            translate([0, 0, DIN_W / 2 + s * DIN_BOLT_PITCH / 2]) {
                translate([-1, 0, 0]) rotate([0, 0, 90]) uh_teardrop_prism(DIN_BOLT_D, DIN_P + 2, MO);
                translate([DIN_P - DIN_NUT_H, 0, 0]) rotate([0, 0, 90])
                    uh_face_extrude(DIN_NUT_H + 1) uh_hex_cell2d(DIN_NUT_AF, MO);
            }
    }
}

// Mounted position behind the holder (u -> +Y, v -> Z at DIN_Z, rail axis -> X)
module uh_din_clip_in_use() {
    multmatrix([[0, 0, 1, -DIN_W / 2], [1, 0, 0, 0], [0, 1, 0, DIN_Z], [0, 0, 0, 1]]) uh_din_clip();
}

// TS35 × 7.5 reference rail (1 mm) in the mounted frame; shift_u moves it away from the plate
module uh_din_rail(shift_u = 0, len = 120) {
    multmatrix([[0, 0, 1, -len / 2], [1, 0, 0, 0], [0, 1, 0, DIN_Z], [0, 0, 0, 1]])
        linear_extrude(len) translate([shift_u, 0]) {
            for (s = [-1, 1]) {
                translate([DIN_P, s > 0 ? DIN_E - DIN_LIP_W : -DIN_E]) square([1, DIN_LIP_W]);
                translate([DIN_P, s > 0 ? DIN_E - DIN_LIP_W - 1 : -DIN_E + DIN_LIP_W]) square([DIN_DEPTH, 1]);
            }
            translate([DIN_P + DIN_DEPTH - 1, -(DIN_E - DIN_LIP_W)]) square([1, 2 * (DIN_E - DIN_LIP_W)]);
        }
}

// Clip beside the holder on the same bed
module uh_din_clip_beside() {
    wx = (len(WG_SIDES) > 0 && max(WG_SIDES) > 0) ? wing_len : 0;
    translate([BODY_W / 2 + wx + 10, -BODY_D / 2 - (DIN_V_TOP + DIN_V_BOT) / 2, 0]) uh_din_clip();
}
// ==== end lib/uh_din.scad ====
// ==== begin lib/uh_mount.scad ====
// =====================================================================
//  UniHolder — lib/uh_mount.scad                       ST-3, ST-4, ST-5
//  Wall mounting: back holes (plain, countersink, counterbore, keyhole) seated
//  flush in the back wall, wings with holes and gussets (ST-3); vertical and
//  horizontal pole saddles with zip-tie tunnels (ST-4). Nothing enters the item space.
//  Publishes keepout rectangles so the hexagon pattern avoids mounts.
//
//  Reads the Customizer parameters of uniholder.scad and the values of
//  uh_body.scad. Include after uh_body.scad.
//
//  Public API
//    Modules    uh_mount_checks  uh_mount_external  uh_mount_cutters
//    Values     BH_* (back holes)  WG_* (wings)  POLE_*, PV_*, PH_* (pole mount)
//    Functions  uh_mount_keepouts(wall)
// =====================================================================

RIM = 2.4;   // material kept around a screw head (hexagon keepouts)

// n positions from lo to hi: spread evenly (pitch = 0) or at a pitch, centred
function _uh_spread(n, lo, hi, pitch, single) =
      n <= 1 ? [single]
    : let(pmax = (hi - lo) / (n - 1),
          p    = pitch > 0 ? min(pitch, pmax) : pmax)
      [for (i = [0:n - 1]) (lo + hi) / 2 + (i - (n - 1) / 2) * p];

// ---- back holes ---------------------------------------------------------

BH_KEY  = BH_STYLE == "keyhole";
BH_SLOT = BH_KEY ? BH_HEAD + 2 : 0;                         // keyhole travel
BH_R    = BH_HEAD / 2 + RIM;                                // hexagons keep clear around a hole
BH_TOP  = uh_teardrop_apex(BH_HEAD / 2, MO) + RIM;          // ... and above it

// hole centres: heads stay on the flat inner back face, clear of corner radii, cove and rim
BH_X_LIM = IN_W / 2 - R_IN[2] - BH_HEAD / 2 - 1;
BH_Z_MIN = floor_t + COVE + BH_HEAD / 2 + 1;
BH_Z_MAX = BODY_H - max(C_TOP_OUT, C_TOP_IN) - uh_teardrop_apex(BH_HEAD / 2, MO) - BH_SLOT - 2;

// DIN clip bolt pattern (ST-5): two holes along the rail at the rail height
DIN_ON   = BH_DIN;
DIN_Z    = uh_clamp(din_rail_z > 0 ? din_rail_z : max(BODY_H / 2, -DIN_V_BOT + 1), BH_Z_MIN, BH_Z_MAX);
DIN_KEEP = [-DIN_W / 2 - 1, DIN_Z + DIN_V_BOT - 1, DIN_W / 2 + 1, DIN_Z + DIN_V_TOP + 1];
BH_COLS  = max(1, min(back_hole_cols, floor(2 * BH_X_LIM / (BH_HEAD + 2)) + 1));
BH_ROWS  = max(1, min(back_hole_rows, floor((BH_Z_MAX - BH_Z_MIN) / (BH_HEAD + 2)) + 1));
BH_POS   = !BH_ACTIVE ? [] : DIN_ON ? [[-DIN_BOLT_PITCH / 2, DIN_Z], [DIN_BOLT_PITCH / 2, DIN_Z]] :
    [for (x = _uh_spread(BH_COLS, -BH_X_LIM, BH_X_LIM, back_hole_pitch_x, 0))
        for (z = _uh_spread(BH_ROWS, BH_Z_MIN, BH_Z_MAX, back_hole_pitch_z,
                            BH_Z_MIN + (BH_Z_MAX - BH_Z_MIN) * 2 / 3))
            [x, z]];

// ---- wings ----------------------------------------------------------------

WG_SIDES  = wings == "left" ? [-1] : wings == "right" ? [1] : wings == "both" ? [-1, 1] : [];
WG_HEAD   = 2 * wing_hole_d;
WG_SLOT   = wing_hole_style == "slot" ? 6 : 0;
WG_R      = 3;                                              // tip corner radius (E4-safe)
WG_CH     = min(0.8, wing_t / 4);                           // front-face chamfer
WG_TIP_H  = (wing_h <= 0 || wing_h >= BODY_H) ? BODY_H
          : uh_clamp_warn(wing_h, WG_HEAD + 8, BODY_H, "wing_h");
WG_RAISED = wing_align == "top" && WG_TIP_H < BODY_H;
WG_Z_TOP  = WG_RAISED ? BODY_H : WG_TIP_H;
WG_ROOT_X = BODY_W / 2 - max(wall_t, R_OUT[2]);             // plate starts inside the body
WG_LEN_T  = BODY_W / 2 + wing_len - WG_ROOT_X;              // outline length, root to tip
WG_Z_ROOT = WG_RAISED ? WG_Z_TOP - WG_TIP_H - uh_rise(WG_LEN_T, MO) : 0;   // < 0 is clipped
WG_G_RAW  = wing_gusset ? min(0.4 * wing_len, 10, wing_len - WG_HEAD - 3) : 0;
WG_G      = WG_G_RAW >= 3 ? WG_G_RAW : 0;                   // gusset length along the wing
WG_HOLE_X = BODY_W / 2 + (WG_G + wing_len) / 2;             // centred in the free wing length
WG_UNDER  = WG_RAISED ? max(0, WG_Z_ROOT + uh_rise(WG_HOLE_X - WG_ROOT_X, MO)) : 0;
WG_HZ_MIN = WG_UNDER + max(C_BOT, WG_CH) + WG_HEAD / 2 + 2;
WG_HZ_MAX = WG_Z_TOP - uh_teardrop_apex(WG_HEAD / 2, MO) - WG_SLOT - 2;
WG_N      = max(1, min(wing_hole_count, floor((WG_HZ_MAX - WG_HZ_MIN) / (WG_HEAD + 2)) + 1));
WG_HZ     = _uh_spread(WG_N, WG_HZ_MIN, WG_HZ_MAX, 0, (WG_HZ_MIN + WG_HZ_MAX) / 2);

// ---- pole mount (ST-4) -------------------------------------------------------
// A block behind the back wall carries a V-cradle for the pole; zip ties run through
// tunnels between the back face and the cradle apex and wrap around the pole.

POLE_ON    = pole_mount != "none";
POLE_VERT  = pole_mount == "vertical";
TIE_FLARE  = 1.0;                                            // flare at each tunnel exit
TIE_W      = tie_w + tie_clr;                                // tunnel size = zip tie + clearance
TIE_T      = tie_t + tie_clr;
POLE_RIM   = 3.0;                                            // material beside the groove
POLE_TH    = (POLE_ON && !POLE_VERT)                         // horizontal: upper flank >= beta (P2)
           ? uh_clamp_warn(pole_v_angle, 2 * uh_beta(MO), 150, "pole_v_angle") : pole_v_angle;
POLE_C     = (pole_d / 2) * pow(cos(POLE_TH / 2), 2) / sin(POLE_TH / 2);   // contact depth below apex
POLE_G     = POLE_C + 2;                                     // groove depth
POLE_YA    = TIE_T + 2 * TIE_FLARE + 2 * MIN_SKIN;           // apex distance from the back face
POLE_DEPTH = POLE_YA + POLE_G;                               // block depth behind the back face
POLE_SIZE  = 2 * POLE_G * tan(POLE_TH / 2) + 2 * POLE_RIM;   // block width (vertical) or height (horizontal)
POLE_YT    = POLE_YA / 2;                                    // tunnel centre
POLE_FIX   = BACK_T / 2;                                     // block reaches into the back wall
TIE_PITCH  = TIE_W + 2 * TIE_FLARE + 4;                      // minimum tunnel spacing

// vertical pole: full-height block, horizontal tunnels spread over the height
PV_Z_LO = TIE_W / 2 + TIE_FLARE + uh_roof_h(TIE_T + 2 * TIE_FLARE, MO) + 4;
PV_Z_HI = BODY_H - C_TOP_OUT - PV_Z_LO;
PV_N    = max(1, min(tie_count, floor((PV_Z_HI - PV_Z_LO) / TIE_PITCH) + 1));
PV_ZS   = _uh_spread(PV_N, PV_Z_LO, PV_Z_HI, 0, BODY_H / 2);

// horizontal pole: block along the rim with a support slope below, vertical tunnels
PH_L    = BODY_W - 2 * max(R_OUT[2], 1);
PH_ZB   = BODY_H - POLE_SIZE;                                // underside at the rear face
PH_ZC   = BODY_H - POLE_SIZE / 2;                            // cradle axis height
PH_X_LO = -PH_L / 2 + TIE_W / 2 + TIE_FLARE + 3;
PH_N    = max(1, min(tie_count, floor((-2 * PH_X_LO) / TIE_PITCH) + 1));
PH_XS   = _uh_spread(PH_N, PH_X_LO, -PH_X_LO, 0, 0);
function _uh_ph_slope_z(y) = PH_ZB - uh_rise(POLE_DEPTH - y, MO);

POLE_N    = POLE_VERT ? PV_N : PH_N;
POLE_KEEP = POLE_VERT ? [-POLE_SIZE / 2 - 1, -1, POLE_SIZE / 2 + 1, BODY_H + 1]
                      : [-PH_L / 2 - 1, _uh_ph_slope_z(0) - 1, PH_L / 2 + 1, BODY_H + 1];

// ---- checks -----------------------------------------------------------------

module uh_mount_checks() {
    if (BH_ACTIVE) {
        assert(BH_X_LIM >= 0 && BH_Z_MAX >= BH_Z_MIN,
            "UniHolder: the back wall is too small for these back holes - reduce back_hole_d or the head size");
        if (!DIN_ON) uh_warn(BH_COLS == back_hole_cols && BH_ROWS == back_hole_rows,
            str("back holes reduced to ", BH_COLS, " x ", BH_ROWS, " so the heads do not overlap"));
        if (!DIN_ON) uh_warn(back_hole_pitch_x == 0 || BH_COLS < 2 || back_hole_pitch_x <= 2 * BH_X_LIM / (BH_COLS - 1),
            "back_hole_pitch_x reduced to fit the back wall");
        if (!DIN_ON) uh_warn(back_hole_pitch_z == 0 || BH_ROWS < 2 || back_hole_pitch_z <= (BH_Z_MAX - BH_Z_MIN) / (BH_ROWS - 1),
            "back_hole_pitch_z reduced to fit the back wall");
        uh_info(str("back holes: ", len(BH_POS), " x ", BH_STYLE, " d ", BH_DIA,
                    BACK_T > back_t ? str(", back wall thickened to ", BACK_T, " mm") : ""));
        uh_warn(size_mode == "inner" || BACK_T <= back_t,
            str("back wall thickened to ", BACK_T, " mm to seat the screw heads - inner depth is reduced"));
    }
    if (len(WG_SIDES) > 0) {
        assert(wing_len - WG_G >= WG_HEAD + 2, "UniHolder: wing_len is too short for wing_hole_d");
        assert(WG_HZ_MAX >= WG_HZ_MIN, "UniHolder: the wing is too low for its holes - increase wing_h");
        uh_warn(WG_N == wing_hole_count, str("wing_hole_count reduced to ", WG_N, " to fit the wing"));
        uh_warn(!wing_gusset || WG_G > 0, "wing is too short for a gusset - gusset omitted");
        uh_info(str("wings: ", wings, ", ", WG_N, " holes each, tip height ", WG_TIP_H, " mm"));
    }
    if (POLE_ON) {
        assert(POLE_VERT || POLE_SIZE <= BODY_H,
            "UniHolder: the holder is too low for a horizontal pole mount of this diameter");
        uh_warn(!POLE_VERT || POLE_SIZE <= BODY_W, "the pole block is wider than the holder");
        uh_warn(POLE_N == tie_count, str("tie_count reduced to ", POLE_N, " to fit the pole block"));
        if (back_holes) uh_info("back holes are not used with a pole mount");
        uh_info(str("pole mount: ", pole_mount, ", pole d ", pole_d, " mm, V ", POLE_TH, " deg, block ",
                    POLE_SIZE, " x ", POLE_DEPTH, " mm, ", POLE_N, " zip-tie tunnels ", TIE_W, " x ", TIE_T, " mm"));
    }
    if (din_holes) {
        uh_warn(pole_mount == "none", "din_holes are ignored with a pole mount");
        if (DIN_ON) {
            assert(BH_X_LIM >= DIN_BOLT_PITCH / 2,
                "UniHolder: the holder is too narrow for the DIN clip bolts - increase size_x");
            uh_warn(back_hole_style != "keyhole", "keyholes cannot hold the DIN clip - countersunk holes are used");
            uh_warn(DIN_W / 2 <= BODY_W / 2 - R_OUT[2], "the DIN clip is wider than the flat back face");
            uh_warn(DIN_Z + DIN_V_BOT >= 0 && DIN_Z + DIN_V_TOP <= BODY_H, "the DIN clip reaches beyond the holder height");
            uh_info(str("DIN clip: rail centre at z = ", DIN_Z, " mm; clip width ", DIN_W, " mm; fix with 2 x ",
                        din_bolt, " x ", DIN_SCREW_L,
                        BH_STYLE == "counterbore" ? " socket head cap screws" : BH_STYLE == "plain" ? " screws" : " countersunk screws",
                        " and 2 x ", din_bolt, " nuts"));
            if (part == "holder")
                uh_info("the DIN clip is a separate part - set part = din_clip, holder_and_clip or din_preview to see it");
        }
    }
    if (part == "din_preview") {
        uh_warn(false, "part = din_preview shows the clip mounted on its rail for viewing - do not print this export");
        uh_warn(DIN_ON, "din_preview: set din_holes = true so the holder gets the clip bolt holes");
    }
}

// ---- keepouts for the hexagon pattern ---------------------------------------

function uh_mount_keepouts(wall) =
      wall == "back" ? concat([for (p = BH_POS) [p[0] - BH_R, p[1] - BH_R, p[0] + BH_R, p[1] + BH_TOP + BH_SLOT]],
                              POLE_ON ? [POLE_KEEP] : [], DIN_ON ? [DIN_KEEP] : [])
    : ((wall == "left"  && len([for (s = WG_SIDES) if (s < 0) s]) > 0) ||
       (wall == "right" && len([for (s = WG_SIDES) if (s > 0) s]) > 0))
          ? [[-wing_t - WG_G - wall_t - 1, max(0, WG_Z_ROOT) - 1, 1, WG_Z_TOP + 1]]
    : [];

// ---- geometry -----------------------------------------------------------------

module uh_mount_external() {
    for (s = WG_SIDES)
        if (s > 0) _uh_wing_right();
        else mirror([1, 0, 0]) _uh_wing_right();
    if (POLE_ON) _uh_pole_block();
}

module uh_mount_cutters() {
    for (p = BH_POS)
        translate([p[0], 0, p[1]])
            if (BH_KEY) uh_keyhole(BH_DIA, BH_HEAD, BH_SLOT, KEY_SKIN, KEY_HEAD, 0, MO);
            else        uh_screw_hole(BH_DIA, BACK_T, BH_STYLE, BH_HEAD, CB_DEPTH, 90, 2, 0, MO);
    for (s = WG_SIDES, z = WG_HZ)
        translate([s * WG_HOLE_X, 0, z])
            uh_screw_hole(wing_hole_d, wing_t, wing_hole_style == "countersink" ? "countersink" : "plain",
                          WG_HEAD, 3, 90, 1, WG_SLOT, MO);
    if (POLE_ON) {
        _uh_pole_groove();
        _uh_pole_tunnels();
    }
}

// Wing outline in (x, z): cantilever from the root, clipped at the bed
module _uh_wing_outline() {
    intersection() {
        translate([WG_ROOT_X, WG_Z_ROOT])
            uh_cantilever2d(WG_LEN_T, WG_Z_TOP - WG_Z_ROOT, MO, WG_R, on_bed = !WG_RAISED);
        translate([WG_ROOT_X - 1, 0]) square([WG_LEN_T + 2, BODY_H + 1]);
    }
}

// Right wing (+X); the left wing is its mirror image
module _uh_wing_right() {
    rf = max(0.2, min(1.5, wing_t / 2 - 0.2));
    tb = wing_t >= BACK_T ? BACK_T - 0.2 : wing_t;          // stay 0.2 mm off the cavity's back face
    intersection() {
        // plate: flush back face, chamfered front face and bed edges
        uh_chamfered_plate(wing_t, c_far = WG_CH, c_near = C_BOT, dir = -1, max_overhang = MO)
            _uh_wing_outline();
        // plan view: filleted tip edges (E1); inside the body only within wall material,
    // 0.2 mm clear of the cavity faces so no faces coincide
        translate([0, 0, -1]) linear_extrude(BODY_H + 2, convexity = 4)
            intersection() {
                translate([WG_ROOT_X - 1, -wing_t])
                    uh_rrect4([WG_LEN_T + 1, wing_t], [0, rf, rf, 0], center = false);
                union() {
                    translate([WG_ROOT_X - 1, -tb]) square([WG_LEN_T + 2, tb]);
                    translate([BODY_W / 2 - wall_t + 0.2, -wing_t]) square([wing_len + wall_t + 0.8, wing_t]);
                }
            }
    }
    // gusset: vertical 45° fin between wing front face and side wall, following the wing outline
    if (WG_G > 0)
        intersection() {
            translate([0, 0, -1]) linear_extrude(BODY_H + 2)
                polygon([[BODY_W / 2 - wall_t + 0.2, -wing_t + UH_EPS],
                         [BODY_W / 2 + WG_G,   -wing_t + UH_EPS],
                         [BODY_W / 2 - wall_t + 0.2, -wing_t - WG_G - wall_t]]);
            translate([0, 1, 0]) uh_face_extrude(wing_t + WG_G + wall_t + 2) _uh_wing_outline();
        }
}

// ---- pole mount geometry (ST-4) ---------------------------------------------------

module _uh_pole_block() {
    if (POLE_VERT)   // stands on the bed: no overhang; rear vertical edges rounded for the ties
        uh_chamfered_extrude(BODY_H, C_BOT, C_TOP_OUT, MO)
            translate([-POLE_SIZE / 2, -POLE_FIX])
                uh_rrect4([POLE_SIZE, POLE_DEPTH + POLE_FIX], [0, 0, 2, 2], center = false);
    else             // hangs at the rim: support slope below (P6), clipped at the bed
        translate([0, -POLE_FIX, 0])
            uh_supported_prism(POLE_DEPTH + POLE_FIX, MO, dir = 1)
                translate([-PH_L / 2, PH_ZB]) uh_rrect4([PH_L, POLE_SIZE], [2, 2, 0, 0], center = false);
}

// V-cradle; the horizontal one has its upper flank at >= beta above horizontal
module _uh_pole_groove() {
    ext = POLE_G + 1;
    hw  = ext * tan(POLE_TH / 2);
    if (POLE_VERT)
        translate([0, 0, -1]) linear_extrude(BODY_H + 2, convexity = 2)
            polygon([[0, POLE_YA], [hw, POLE_YA + ext], [-hw, POLE_YA + ext]]);
    else
        translate([0, 0, PH_ZC]) rotate([90, 0, 90])
            linear_extrude(PH_L + 2, center = true, convexity = 2)
                polygon([[POLE_YA, 0], [POLE_YA + ext, hw], [POLE_YA + ext, -hw]]);
}

// Zip-tie tunnels between the back face and the cradle apex
module _uh_pole_tunnels() {
    if (POLE_VERT)
        for (z = PV_ZS)
            translate([0, POLE_YT, z]) uh_tunnel(TIE_W, TIE_T, POLE_SIZE, TIE_FLARE, "x", MO);
    else
        for (x = PH_XS) {
            z0 = max(0, _uh_ph_slope_z(POLE_YT - TIE_T / 2 - TIE_FLARE)) - 0.5;
            z1 = BODY_H + 0.5;
            translate([x, POLE_YT, (z0 + z1) / 2]) uh_tunnel(TIE_W, TIE_T, z1 - z0, TIE_FLARE, "z", MO);
        }
}
// ==== end lib/uh_mount.scad ====
$fa = uh_quality(quality)[0];
$fs = uh_quality(quality)[1];

// Test hooks (not shown in the Customizer):
//   cavity_probe      what intrudes into the item space - must be empty
//   din_fit           holder, clip and a TS35 rail in their mounted positions
//   din_interference  clip and rail overlap at rest - only the spring preload
//   din_pullout       overlap with the rail moved 1 mm off the plate - the teeth hold
debug_view = "none";

uh_body_checks();
uh_mount_checks();

if      (debug_view == "cavity_probe")     intersection() { uh_holder(); uh_item_space(); }
else if (debug_view == "din_fit")          { color("teal") uh_holder(); color("orange") uh_din_clip_in_use(); color("silver") uh_din_rail(); }
else if (debug_view == "din_interference") intersection() { uh_din_clip_in_use(); uh_din_rail(); }
else if (debug_view == "din_pullout")      intersection() { uh_din_clip_in_use(); uh_din_rail(1); }
else if (part == "din_clip")               uh_din_clip();
else if (part == "holder_and_clip")        { uh_holder(); uh_din_clip_beside(); }
else if (part == "din_preview")            { uh_holder(); color("orange") uh_din_clip_in_use(); %uh_din_rail(); }
else                                       uh_holder();

// Assembly order: shell − cavity, add mount features, then cut
// perforations, the front opening and the mount holes last.
module uh_holder() {
    difference() {
        union() {
            difference() {
                uh_outer_shell();
                uh_cavity();
            }
            uh_mount_external();   // wings and gussets
        }
        uh_perforations();         // hexagons, clear of mount keepouts
        uh_front_opening();
        uh_mount_cutters();        // back holes and wing holes
    }
}
