#!/usr/bin/env python3
"""UniHolder - tools/build_single_file.py                               (ST-5)

Inlines every `include <lib/...>` of uniholder.scad into one file for online
Customizers: uniholder_customizer.scad. Parameters stay at the top, so
the Customizer tabs are unchanged.
"""
import pathlib
import re

root = pathlib.Path(__file__).resolve().parent.parent
src = (root / "uniholder.scad").read_text()


def inline(match):
    name = match.group(1)
    return f"// ==== begin {name} ====\n{(root / name).read_text().rstrip()}\n// ==== end {name} ===="


out = re.sub(r"^include <(lib/[^>]+)>\s*$", inline, src, flags=re.M)
assert not re.search(r"^\s*include\s*<", out, flags=re.M), "unresolved include"
dst = root / "uniholder_customizer.scad"
banner = ("// UniHolder - single-file Customizer version, generated by tools/build_single_file.py.\n"
          "// Same model as uniholder.scad + lib/ in one file (tested identical geometry).\n")
dst.write_text(banner + out)
print(f"{dst.relative_to(root)}: {len(out.splitlines())} lines")
